# Header
menu:
  主页: /
  所有文章: /archives
  类别: /categories

# SubNav
subnav:
  github: "https://github.com/anbulang"
  weibo: "http://weibo.com/3235300780"
  #zhihu: "#"
  douban: "http://www.douban.com/people/anbulang/"
  mail: "anbulang1@gmail.com"
  #facebook: "https://www.facebook.com"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-57958205-1'
favicon: /favicon.png

#你的头像url
avatar: "http://s.gravatar.com/avatar/76352a4260306c5ef961b9ac41f6ff23?s=200"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: An ignorant coder majoring in BME, a little bit obsessive and z-turn.
